Online_Retail Analysis

Step 1 : import library requirement

In [28]:
import numpy as np
import pandas as pd

Step 2.1 : import Dataset

In [29]:
Online_Retail=pd.read_csv(r"C:\Users\Lap Tech\Desktop\online_retail\online_retail_II.csv")

Step 2.2 Backup Dataset

In [30]:
Online_Retail_Backup=Online_Retail.copy()

Step 3 : EDA ( Explory Data Analysis )

In [31]:
Online_Retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  str
 1   StockCode    541910 non-null  str
 2   Description  540456 non-null  str
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  str
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [32]:
Online_Retail.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536368,22960,JAM MAKING SET WITH JARS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom

In [33]:
Online_Retail.tail(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,12/9/2011 12:50,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,12/9/2011 12:50,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,12/9/2011 12:50,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,12/9/2011 12:50,18.00,12680.0,France

In [34]:
Online_Retail.sample(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
484166,577524,23275,SET OF 3 HANGING OWLS OLLIE BEAK,1,11/20/2011 13:33,1.25,16905.0,United Kingdom
48405,540468,22079,RIBBON REEL HEARTS DESIGN,1,1/7/2011 13:55,3.36,NaN,United Kingdom
284934,561893,22502,PICNIC BASKET WICKER SMALL,1,7/31/2011 14:39,5.95,12942.0,United Kingdom
76091,542619,22423,REGENCY CAKESTAND 3 TIER,1,1/30/2011 15:54,12.75,13869.0,United Kingdom
233221,557466,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,10,6/20/2011 13:08,2.08,13815.0,Germany
14576,537604,22558,CLOTHES PEGS RETROSPOT PACK 24,48,12/7/2010 13:01,1.25,13488.0,United Kingdom
512941,579522,23238,SET OF 4 KNICK KNACK TINS LONDON,6,11/30/2011 8:04,4.15,14432.0,United Kingdom
124779,546990,22071,SMALL WHITE RETROSPOT MUG IN BOX,6,3/18/2011 12:59,3.75,14315.0,United Kingdom
394294,570871,23521,WALL ART CAT AND BIRD,1,10/12/2011 16:36,5.79,NaN,United Kingdom
306714,563837,22386,JUMBO BAG PINK POLKADOT,10,8/19/2011 13:03,2.08,15078.0,United Kingdom

In [35]:
Online_Retail.describe()

            Quantity          Price    Customer ID
count  541910.000000  541910.000000  406830.000000
mean        9.552234       4.611138   15287.684160
std       218.080957      96.759765    1713.603074
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [36]:
print('Duplicate_Value : \n' ,Online_Retail.duplicated().sum())
print('Null_Values Per Columns : \n' ,Online_Retail.isnull().sum())
print('Total Null_Values : \n' ,Online_Retail.isnull().sum().sum())

Duplicate_Value :
 5268
Null_Values Per Columns :
 Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64
Total Null_Values :
 136534

Step 4 : Data Cleaning

In [37]:
# Remove Duplicate Values
Online_Retail.drop_duplicates(inplace=True)

In [38]:
print('Duplicate_Value : ' ,Online_Retail.duplicated().sum())

Duplicate_Value :  0

In [39]:
# Handling Missing Values
Online_Retail.dropna(inplace=True)

In [40]:
print('Null_Values Per Columns : \n' ,Online_Retail.isnull().sum())
print('Total Null_Values : ' ,Online_Retail.isnull().sum().sum())

Null_Values Per Columns :
 Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64
Total Null_Values :  0

In [41]:
# Change Data Type
Online_Retail['InvoiceDate'] = pd.to_datetime(Online_Retail['InvoiceDate'])

In [42]:

Online_Retail['Country']=Online_Retail['Country'].replace({
    'EIR':'Ireland',
    'RSA':'South Africa',
    'USA':'United States',
    'European Community':'United Kingdom',
    'Unspecified':'United Kingdom'})
Online_Retail['Country']=Online_Retail['Country'].astype('category')

In [43]:
Online_Retail.info()

<class 'pandas.DataFrame'>
Index: 401605 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      401605 non-null  str
 1   StockCode    401605 non-null  str
 2   Description  401605 non-null  str
 3   Quantity     401605 non-null  int64
 4   InvoiceDate  401605 non-null  datetime64[us]
 5   Price        401605 non-null  float64
 6   Customer ID  401605 non-null  float64
 7   Country      401605 non-null  category
dtypes: category(1), datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 24.9 MB

Step 5 : Feature Engineering

In [44]:
# Export Total_Sales

Online_Retail['Total Sales']=(
Online_Retail['Price']*Online_Retail['Quantity'])
Online_Retail['Total Sales']=round(Online_Retail['Total Sales'],2)

In [45]:
# Export Year, Month, Quarter & Day

Online_Retail['Year']=Online_Retail['InvoiceDate'].dt.year
Online_Retail['Month']=Online_Retail['InvoiceDate'].dt.month
Online_Retail['Month_Name']=Online_Retail['InvoiceDate'].dt.month_name()
Online_Retail['Quarter']=Online_Retail['InvoiceDate'].dt.quarter
Online_Retail['Day']=Online_Retail['InvoiceDate'].dt.day
Online_Retail['Day_Name']=Online_Retail['InvoiceDate'].dt.day_name()